[{
    "company_name":"Google",
    "date":ISODate("2020-09-15"),
    "students_appeared":"Eva,Keerthana,Suba,Vinotha,Hepshi"
},
{
    "company_name":" Apple",
    "date":ISODate("2020-10-06"),
    "students_appeared":"Raja,Sanjay,Zaheer,Santhos,Mohana"
},
{
    "company_name":"TCS",
    "date":ISODate("2020-10-25"),
    "students_appeared":"Nirmala,Sakthi,sri,abi"
},
{
    "company_name":"Zoho",
    "date":ISODate("2020-11-05"),
    "students_appeared":"Sanjay,Naveen,Kalai,Mani"
},
{
    "company_name":"CTS",
    "date":ISODate("2020-11-25"),
    "students_appeared":"Zaheer,Sameer,Rahul,Arun"
}]
